// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbaStats.Data;

namespace NbaStats.Data.Migrations
{
    [DbContext(typeof(NbaStatsDbContext))]
    partial class NbaStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NbaStats.Domain.Games.State.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AwayTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("AwayTeamName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<long>("HomeTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("HomeTeamName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamName");

                    b.HasIndex("HomeTeamName");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NbaStats.Domain.Teams.State.Team", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Name = "Atlanta Hawks"
                        },
                        new
                        {
                            Name = "Boston Celtics"
                        },
                        new
                        {
                            Name = "Brooklyn Nets"
                        },
                        new
                        {
                            Name = "Charlotte Hornets"
                        },
                        new
                        {
                            Name = "Chicago Bulls"
                        },
                        new
                        {
                            Name = "Cleveland Cavaliers"
                        },
                        new
                        {
                            Name = "Dallas Mavericks"
                        },
                        new
                        {
                            Name = "Denver Nuggers"
                        },
                        new
                        {
                            Name = "Detroit Pistons"
                        },
                        new
                        {
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Name = "Houston Rockets"
                        },
                        new
                        {
                            Name = "Indiana Pacers"
                        },
                        new
                        {
                            Name = "Los Angeles Clippers"
                        },
                        new
                        {
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            Name = "Memphis Grizzlies"
                        },
                        new
                        {
                            Name = "Miami Heat"
                        },
                        new
                        {
                            Name = "Milwaukee Bucks"
                        },
                        new
                        {
                            Name = "Minnesota Timberwolves"
                        },
                        new
                        {
                            Name = "New Orleans Pelicans"
                        },
                        new
                        {
                            Name = "New York Knicks"
                        },
                        new
                        {
                            Name = "Oklahoma City Thunder"
                        },
                        new
                        {
                            Name = "Orlando Magic"
                        },
                        new
                        {
                            Name = "Philadelphia 76ers"
                        },
                        new
                        {
                            Name = "Phoenix Suns"
                        },
                        new
                        {
                            Name = "Portland Trail Blazers"
                        },
                        new
                        {
                            Name = "Sacramento Kings"
                        },
                        new
                        {
                            Name = "San Antonio Spurs"
                        },
                        new
                        {
                            Name = "Toronto Raptors"
                        },
                        new
                        {
                            Name = "Utah Jazz"
                        },
                        new
                        {
                            Name = "Washington Wizards"
                        });
                });

            modelBuilder.Entity("NbaStats.Domain.Games.State.Game", b =>
                {
                    b.HasOne("NbaStats.Domain.Teams.State.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamName");

                    b.HasOne("NbaStats.Domain.Teams.State.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamName");
                });
#pragma warning restore 612, 618
        }
    }
}
